FROM node:22-alpine

WORKDIR /app

COPY src/data-preparation/biz/package.json \
     ./package.json

RUN npm install \
    --omit=dev \
    --no-audit \
    --no-fund

COPY src/data-preparation/biz/validate-reconciliation.js \
     ./validate-reconciliation.js

ENTRYPOINT ["node","/app/validate-reconciliation.js"]