FROM node:22-alpine@sha256:c610fcdfb1d5b4740dd70c284ed3cb16bb857e0f7166196e36a5501df7a3aa32

WORKDIR /app

COPY src/data-preparation/biz/package.json \
     ./package.json

RUN npm install \
    --omit=dev \
    --no-audit \
    --no-fund

COPY src/data-preparation/biz/validate-reconciliation.js \
     ./validate-reconciliation.js

ENTRYPOINT ["node","/app/validate-reconciliation.js"]