FROM node:22-alpine

WORKDIR /app

COPY src/data-preparation/biz/package.json ./package.json

RUN npm install \
    --omit=dev \
    --no-audit \
    --no-fund

COPY src/data-preparation/biz/prepare-biz-events.js \
     ./prepare-biz-events.js

ENTRYPOINT ["node", "/app/prepare-biz-events.js"]