apiVersion: v2
name: pagopa-gpd-technical-support
description: Microservice exposing technical support APIs for GPD
type: application
version: 0.20.0
appVersion: 0.0.5-1-PIDM-2314-operation-timeout
dependencies:
  - name: microservice-chart
    version: 8.4.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
