apiVersion: v2
name: pagopa-gpd-technical-support
description: Microservice exposing technical support APIs for GPD
type: application
version: 0.5.0
appVersion: 0.0.1-4-PIDM-1995-debt-positions-status-reconciliation
dependencies:
  - name: microservice-chart
    version: 8.4.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
